#! /bin/bash
shopt -s nocasematch
md=`date +%m-%d`
if [[ "$QUERY_STRING" = "" ]]
then
	/bin/echo Content-type: text/html
	/bin/echo
	/usr/bin/php -f wms_info.php KIWE
elif [[ "$QUERY_STRING" = *request=getcapabilities* ]]
then
	/bin/echo Content-type: text/xml
	/bin/echo
	/bin/cat /srv/cp/capabilities.xml
else
	MS_MAPFILE=/srv/cp/cp.map
	export MS_MAPFILE
	/usr/lib/cgi-bin/mapserv
fi
